# Generated by Django 4.2.16 on 2024-11-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='mediaproject/images')),
                ('chapters', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('puntuation', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
