# Generated by Django 4.2.16 on 2024-11-26 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mproject', '0002_movie_description_movie_genre_movie_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
